### ISSUE TITLE
Installation was failed via docker-compose

### ISSUE THREAD

**Issue by hiroshiyui** [operable/cog#1045]
Hello,

I just followed http://docs.operable.io/docs/installation to set my `SLACK_API_TOKEN` to a valid value and `COG_HOST` to `127.0.0.1`, then run `docker-compose up` but got this error message:

```
$ docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 110, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.5/site-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/lib/python3.5/site-packages/compose/cli/command.py", line 102, in get_project
    config_data = config.load(config_details)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 319, in load
    service_dicts = load_services(config_details, main_file)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 407, in load_services
    service_config = merge_services(service_config, next_config)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 398, in merge_services
    for name in all_service_names
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 398, in <dictcomp>
    for name in all_service_names
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 689, in merge_service_dicts_from_files
    new_service = merge_service_dicts(base, override, version)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 754, in merge_service_dicts
    md.merge_field(field, merge_unique_items_lists, default=[])
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 713, in merge_field
    self.override.get(field, default))
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 771, in merge_unique_items_lists
    return sorted(set().union(base, override))
TypeError: unorderable types: int() < str()
```

System information:
* OS: Arch Linux (x86_64)
* Docker: 1.12.1
* docker-compose: 1.8.0

While running on my macOS machine, with `docker-machine`, there is no such error message and docker-compose just runs fine. Is there something I am missed?

**Comment by hiroshiyui** [comment]
Excuse me, it seems like an issue of `docker-compose`, while using an different copy from Docker official repository, the command runs without errors.
