### ISSUE TITLE
Slack adapter crashes unescaping links

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1067]
```
2016-10-17T14:21:38.0994  (Cog.Chat.Slack.Connector:3) [error] no case clause matching: nil
2016-10-17T14:21:38.0997  (Cog.Chat.Slack.Connector:3) [error]     (cog) lib/cog/chat/slack/formatter.ex:51: anonymous fn/1 in Cog.Chat.Slack.Formatter
.unescape_links/1
    (cog) lib/cog/chat/slack/formatter.ex:66: Cog.Chat.Slack.Formatter.replace/3
    (cog) lib/cog/chat/slack/connector.ex:279: Cog.Chat.Slack.Connector.annotate_message/2
    (cog) lib/cog/chat/slack/connector.ex:30: Cog.Chat.Slack.Connector.handle_message/2
    (cog) lib/cog/chat/slack/connector.ex:3: Cog.Chat.Slack.Connector.websocket_handle/3
    src/websocket_client.erl:384: :websocket_client.retrieve_frame/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by vanstee** [comment]
This whole module was rewritten with simpler regex replacements and the area the error was coming from is no longer around. Closing this as I'm pretty sure it's already fixed and I'm not sure how I can produce.
