### ISSUE TITLE
Using a join tag inside an each (both using the default item name) crashes greenbar

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1264]
Looks like some kind of overlapping scoping issue when reusing `$item` in an each and a join. If you name the value for the current enumeration in the each tag, green processes the template just fine.

Data:

```
{
  "results": [{
    "people": [
      {"name": "Patrick"},
      {"name": "Kevin"},
      {"name": "Mark"},
      {"name": "Shelton"}
    ]
  }]
}
```

Template:

```
~each var=$results~
~join var=$item.people with=", "~~$item.name~~end~
~end~
```

Stacktrace:

```
** (MatchError) no match of right hand side value: {:error, :already_stored}
    (greenbar) lib/greenbar/tags/join.ex:66: Greenbar.Tags.Join.render/3
    (greenbar) lib/greenbar/tag.ex:276: Greenbar.Tag.render!/6
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:438: :erl_eval.expr/5
    (greenbar) lib/greenbar/tag.ex:300: Greenbar.Tag.render_body!/7
    (greenbar) lib/greenbar/tag.ex:283: Greenbar.Tag.render!/6
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:438: :erl_eval.expr/5
```

**Comment by vanstee** [comment]
Fixed in https://github.com/operable/greenbar/pull/42
