### ISSUE TITLE
Python error when running docker-compose up with the cog compose files

### ISSUE THREAD

**Issue by SuperNami** [operable/cog#1285]
1. Downloaded all the compose files from the installation guide: http://cog-book.operable.io/#_installing_and_running_cog_with_docker_compose

2. Populated the environment variables `SLACK_API_TOKEN` and `COG_HOST`.

3. Run `docker-compose up`, output:

```
[user@pc cog]$ docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 65, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 114, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.5/site-packages/compose/cli/command.py", line 36, in project_from_options
    environment=environment
  File "/usr/lib/python3.5/site-packages/compose/cli/command.py", line 103, in get_project
    config_data = config.load(config_details)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 323, in load
    service_dicts = load_services(config_details, main_file)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 414, in load_services
    service_config = merge_services(service_config, next_config)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 405, in merge_services
    for name in all_service_names
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 405, in <dictcomp>
    for name in all_service_names
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 704, in merge_service_dicts_from_files
    new_service = merge_service_dicts(base, override, version)
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 769, in merge_service_dicts
    md.merge_field(field, merge_unique_items_lists, default=[])
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 728, in merge_field
    self.override.get(field, default))
  File "/usr/lib/python3.5/site-packages/compose/config/config.py", line 788, in merge_unique_items_lists
    return sorted(set().union(base, override))
TypeError: unorderable types: int() < str()
```

**Comment by christophermaier** [comment]
@SuperNami I wasn't able to replicate your issue locally. Here's what I did:

``` sh
$ mkdir -p /tmp/cog-docker-compose-bug
$ cd /tmp/cog-docker-compose-bug/
$ unset COG_HOST
$ unset SLACK_API_TOKEN
$ echo $COG_HOST

$ echo $SLACK_API_TOKEN

$ curl -o docker-compose.yml https://raw.githubusercontent.com/operable/cog/0.16.2/docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2264  100  2264    0     0   2887      0 --:--:-- --:--:-- --:--:--  2887
$ curl -o docker-compose.common.yml https://raw.githubusercontent.com/operable/cog/0.16.2/docker-compose.common.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   226  100   226    0     0    889      0 --:--:-- --:--:-- --:--:--   893
$ curl -o docker-compose.override.yml https://raw.githubusercontent.com/operable/cog/0.16.2/docker-compose.override.slack_example.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   482  100   482    0     0   2102      0 --:--:-- --:--:-- --:--:--  2104
$ export COG_HOST=127.0.0.1
$ export SLACK_API_TOKEN=xoxb-XXXXXXXXXXXXXXXXXX
$ docker-compose up
Creating cogdockercomposebug_postgres_1
Creating cogdockercomposebug_cog_1
Creating cogdockercomposebug_relay_1
Attaching to cogdockercomposebug_postgres_1, cogdockercomposebug_cog_1, cogdockercomposebug_relay_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
...
```

Here's what I'm running:
``` sh
$ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
$ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```
All that comes from Docker for Mac
```
Version 1.12.5 (14777)
Channel: Stable
3e6f00c1dc
```
Running on OS X 10.10.5 

Is there any more detail you can provide about your particular setup? Thanks.

**Comment by SuperNami** [comment]
Thanks for your research efforts. Docker version:

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   7392c3b0ce
 Built:        Wed Dec 28 22:26:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   7392c3b0ce
 Built:        Wed Dec 28 22:26:08 2016
 OS/Arch:      linux/amd64
```

Latest Manjaro linux, kernel version:

`4.8.15-1-MANJARO`

Maybe this has to more with docker-compose specifically. I'll also post a bug report in the docker compose repository.

**Comment by SuperNami** [comment]
Posted at the docker compose issues as well: https://github.com/docker/compose/issues/4299

**Comment by christophermaier** [comment]
Closing for now, as it appears this is not a Cog issue. Happy to reopen if more information surfaces.
