### ISSUE TITLE
`cogctl bundle install` crashes with invalid bundle

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#1363]
At the very least, we need to handle the 422 exception that Cog sends back.

Ideally, we'd also do JSON Schema validation on the client side before sending to the server, but that will involve more work (like extracting the schema definitions from the Spanner project).

Reproduction Steps:

```
$ curl https://raw.githubusercontent.com/cogcmd/circle/master/config.yaml --retry 3 | cogctl --profile=compose bundle install - --enable --relay-group=default
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1040  100  1040    0     0   1218      0 --:--:-- --:--:-- --:--:--  1217
Traceback (most recent call last):
  File "cogctl/cli/decorators.py", line 13, in wrapped
  File "site-packages/click/decorators.py", line 27, in new_func
  File "cogctl/cli/bundle/install.py", line 190, in install
  File "cogctl/api.py", line 184, in install_bundle
  File "cogctl/api.py", line 429, in post
  File "site-packages/requests/models.py", line 893, in raise_for_status
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: http://10.10.2.26:80/v1/bundles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/cogctl", line 3, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "cogctl/cli/decorators.py", line 45, in wrapped
AttributeError: 'list' object has no attribute 'get'
Failed to execute script cogctl
```

**Comment by christophermaier** [comment]
Looks like this fixed itself with operable/cogctl#126
