### ISSUE TITLE
Cog crashes when new user registers (Slack)

### ISSUE THREAD

**Issue by Erreinion** [operable/cog#1380]
I have self-registration on. Behaviour is consistent. Every time a new user interacts with the Cog bot on Slack, cog crashes.

Using the cog Docker container.

By the way, Cog generates hundreds of log messages in a minute when this happens.

Log, first entry:
```
2017-03-16T11:05:58.0172  (Cog.Chat.Adapter:159) [info] Starting
2017-03-16T11:05:58.0186  (Logger.Watcher:92) [error] GenEvent handler {LoggerFileBackend, :cog_log} installed at Logger
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.iolist_to_binary([[42, 42, 32, 87, 101, 98, 115, 111, 99, 107, 101, 116, 32, 104, 97, 110, 100, 108, 101, 114, 32, ['Cog.Chat.Slack.Connector'], 32, 116, 101, 114, 109, 105, 110, 97, 116, 105, 110, 103, '\n', 42, 42, 32, 102, 111, 114, 32, 116, 104, 101, 32, 114, 101, 97, ...], " (truncated)"])
        lib/adz.ex:39: Adz.format_message/1
        lib/adz.ex:23: Adz.text/4
        (logger_file_backend) lib/logger_file_backend.ex:63: LoggerFileBackend.log_event/5
        (elixir) lib/gen_event.ex:1104: GenEvent.do_handler/3
        (elixir) lib/gen_event.ex:945: GenEvent.server_update/5
        (elixir) lib/gen_event.ex:930: GenEvent.server_notify/7
        (elixir) lib/gen_event.ex:903: GenEvent.server_event/4
2017-03-16T11:05:58.0188  () [error] ** State machine #PID<0.1066.0> terminating 
** Last message in was {:EXIT, #PID<0.1065.0>,
 {:handler,
  %RuntimeError{message: "key :email not found in: %{avatar_hash: \"gf87402a69e6\", fields: nil, first_name: \"Adi\", image_192: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0021-192.png\", image_24: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F0180%2Fimg%2Favatars%2Fava_0021-24.png\", image_32: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0021-32.png\", image_48: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F3654%2Fimg%2Favatars%2Fava_0021-48.png\", image_512: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0021-512.png\", image_72: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0021-72.png\", last_name: \"\", real_name: \"Adi\", real_name_normalized: \"Adi\"}"}}}
** When State == :connected
**      Data  == {:state, #PID<0.1065.0>, '<0.1066.0>', {0, 0, 0, 0}, 1883, #Port<0.49527>,
 #PID<0.1068.0>,
 {:proto_state, #Port<0.49527>, '127.0.0.1:32945', 4, "MQTT",
  "emqttc_c2bedd850ede_0a7c426f346c4f7a45ea", true, 90, false,
  {:mqtt_message, 0, false, false, :undefined, :undefined, :undefined},
  "COG_INTERNAL",
  "rBuxSw/+gtZ4H1LCiDCcpl3EmUrizFBqroLBafKvgdoi9XTQCXSmzhDhn2nXU7ML", 103,
  %{"carrier/call/reply/a45f1f2c9e1f42b9af2e3202f7ceeca7" => 0}, %{}, %{}, %{},
  {:gen_logger, :lager_logger, 8}}, [{#PID<0.1065.0>, #Reference<0.0.1.10739>}],
 %{"carrier/call/reply/a45f1f2c9e1f42b9af2e3202f7ceeca7" => {0,
    [#PID<0.1065.0>]}}, [], [], %{}, 1, false,
 {:keepalive, #Port<0.49527>, :send_oct, 34764, 90, {:keepalive, :timeout},
  #Reference<0.0.262145.120875>}, 90, 60, 4, 8, :undefined, :tcp, :undefined,
 {:gen_logger, :lager_logger, 8}, [], []}
** Reason for termination = 
** {:handler,
 %RuntimeError{message: "key :email not found in: %{avatar_hash: \"gf87402a69e6\", fields: nil, first_name: \"Adi\", image_192: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0021-192.png\", image_24: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F0180%2Fimg%2Favatars%2Fava_0021-24.png\", image_32: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=32&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0021-32.png\", image_48: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=48&d=https%3A%2F%2Fa.slack-edge.com%2F3654%2Fimg%2Favatars%2Fava_0021-48.png\", image_512: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0021-512.png\", image_72: \"https://secure.gravatar.com/avatar/f87402a69e621fccc5b2e38362f44c14.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2F66f9%2Fimg%2Favatars%2Fava_0021-72.png\", last_name: \"\", real_name: \"Adi\", real_name_normalized: \"Adi\"}"}}

```

**Comment by Erreinion** [comment]
Is there a way to turn off the requirement for emails, or for cog to handle errors more gracefully?

**Comment by christophermaier** [comment]
May have to do with this recent change to how Slack exposes email addresses: https://api.slack.com/changelog/2016-11-10-addressing-email-addresses

**Comment by christophermaier** [comment]
@Erreinion There isn't currently a way to disable the requirement for emails, as that's also built into Cog's database schema. Not having an email address would also affect the "reset password by email" functionality. We may be able to alter Cog to better account for this, but as of this moment, I don't think there's a "quick fix" for this.
