### ISSUE TITLE
Rework HipChat adapter

### ISSUE THREAD

**Issue by vanstee** [operable/cog#311]
* Upgrade hedwig to the newest version
  * Make sure room names with spaces work
* Add better errors for missing/incorrect config
* Clean up HTTP API code and potentially pull out into it's own lib

**Comment by lhaskins** [comment]
An error that may be related to the needed changes here. Also seen by other in the cogbot room.
```
2016-03-08T16:24:32.0735  (Hedwig.Transports.TCP:45) [info] Outgoing stanza: {:xmlel, "auth", [{"xmlns", "urn:ietf:params:xml:ns:xmpp-sasl"}, {"mechanism", "PLAIN"}], [xmlcdata: "ADQ3OTU0M18zNjM4MzAyAHByM2RAdDBy"]}
2016-03-08T16:24:32.0841  (Hedwig.Transports.TCP:158) [debug] Incoming stanza: "<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>"
2016-03-08T16:24:32.0841  (Hedwig.Transports.TCP:45) [info] Outgoing stanza: {:xmlstreamstart, "stream:stream", [{"to", "chat.hipchat.com"}, {"version", "1.0"}, {"xml:lang", "en"}, {"xmlns", "jabber:client"}, {"xmlns:stream", "http://etherx.jabber.org/streams"}]}
2016-03-08T16:24:32.0855  (Hedwig.Transports.TCP:158) [debug] Incoming stanza: "<stream:stream xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' version='1.0' from='chat.hipchat.com' id='87c298eb7574d816'>"
2016-03-08T16:24:32.0855  (Hedwig.Transports.TCP:158) [debug] Incoming stanza: "<stream:features><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><required/></bind><ver xmlns='http://hipchat.com/protocol/rooms#hash'/><ver xmlns='http://hipchat.com/protocol/users#hash'/></stream:features>"
2016-03-08T16:24:32.0855  (Hedwig.Transports.TCP:45) [info] Outgoing stanza: {:xmlel, "iq", [{"type", "set"}, {"id", "eeeb"}], {:xmlel, "bind", [{"xmlns", "urn:ietf:params:xml:ns:xmpp-bind"}], [{:xmlel, "resource", [], {:xmlcdata, "bot"}}]}}
2016-03-08T16:24:32.0856  (Hedwig.Transports.TCP:45) [info] Outgoing stanza: {:xmlel, "iq", [{"type", "set"}, {"id", "2769"}], {:xmlel, "session", [{"xmlns", "urn:ietf:params:xml:ns:xmpp-session"}], []}}
2016-03-08T16:24:32.0857  () [error] GenServer #PID<0.912.0> terminating
** (ArgumentError) argument error
    (gproc) src/gproc.erl:616: :gproc.reg({:n, :l, "479543_3638302@chat.hipchat.com"})
    (hedwig) lib/hedwig/registry.ex:8: Hedwig.Registry.register/1
    (hedwig) lib/hedwig/client.ex:140: Hedwig.Client.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :register
State: %Hedwig.Client{config: %{client: #PID<0.912.0>, ignore_from_self: true, ignore_from_self?: true, port: 5222, preferred_auth_mechanisms: ["PLAIN"], require_tls?: true, server: "chat.hipchat.com", transport: Hedwig.Transports.TCP, use_compression?: false, use_stream_management?: false}, conn: #PID<0.914.0>, event_manager: #PID<0.913.0>, handlers: [{Cog.Adapters.HipChat.XMPPHandler, %{}}], jid: "479543_3638302@chat.hipchat.com", nickname: "Alien Predator", password: "pr3d@t0r", resource: "bot", rooms: ["479543_bot-testing@conf.hipchat.com"]}
2016-03-08T16:24:32.0874  (Hedwig.Conn:161) [info] Waiting for socket
```
