### ISSUE TITLE
Display help when running `cogctl help`

### ISSUE THREAD

**Issue by vanstee** [operable/cog#629]
Right now we just error which is ugly:

```
› ./cogctl help
** (UndefinedFunctionError) undefined function :error.option_spec/0 (module :error is not available)
    :error.option_spec()
    (cogctl) Cogctl.Optparse.opt_specs/1
    (cogctl) lib/cogctl/optparse.ex:114: Cogctl.Optparse.parse_args/2
    (cogctl) lib/cogctl/optparse.ex:87: Cogctl.Optparse.parse/1
    (cogctl) lib/cogctl.ex:19: Cogctl.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by kevsmith** [comment]
While not great we don't crash at least:

``` shell
14:17:11 samedi:/Users/kevsmith/$ cogctl help
cogctl: Unknown action in 'help'. Did you mean 'relays update'?
14:17:13 samedi:/Users/kevsmith/$
```

**Comment by christophermaier** [comment]
The Python `cogctl` has an awesome help system now.
