### ISSUE TITLE
Cog crashes processing slackbot messages

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#982]
```
2016-09-23T20:06:52.0003  (Cog.Chat.Slack.Connector:3) [error] key :email not found in: %{avatar_hash: "sv1444671949", fields: nil, first_name: "slackbot", image_192: "https://a.slack-edge.com/66f9/img/slackbot_192.png", image_24: "https://a.slack-edge.com/0180/img/slackbot_24.png", image_32: "https://a.slack-edge.com/2fac/plugins/slackbot/assets/service_32.png", image_48: "https://a.slack-edge.com/2fac/plugins/slackbot/assets/service_48.png", image_512: "https://a.slack-edge.com/1801/img/slackbot_512.png", image_72: "https://a.slack-edge.com/0180/img/slackbot_72.png", last_name: "", real_name: "slackbot", real_name_normalized: "slackbot"}
2016-09-23T20:06:52.0004  (Cog.Chat.Slack.Connector:3) [error]     (cog) lib/cog/chat/slack/connector.ex:215: Cog.Chat.Slack.Connector.make_user/1
    (cog) lib/cog/chat/slack/connector.ex:174: Cog.Chat.Slack.Connector.user_by_id/3
    (elixir) lib/enum.ex:2866: Enumerable.Map.do_reduce/3
    (elixir) lib/enum.ex:1657: Enum.reduce_while/3
    (cog) lib/cog/chat/slack/connector.ex:256: Cog.Chat.Slack.Connector.annotate_message/2
    (cog) lib/cog/chat/slack/connector.ex:30: Cog.Chat.Slack.Connector.handle_message/2
    (cog) lib/cog/chat/slack/connector.ex:3: Cog.Chat.Slack.Connector.websocket_handle/3
    src/websocket_client.erl:384: :websocket_client.retrieve_frame/6
```

**Comment by kevsmith** [comment]
Looks like Slack isn't setting the `is_bot` flag on slackbot messages. This causes Cog's Slack provider to interpret the message as coming from a human user which would have an associated profile with entries for email, first_name, last_name, etc.
